### ISSUE TITLE
MongoDB server selection error

### ISSUE THREAD

**Issue by DavidDubinin** [algo7/tf2_rcon_misc#37]
hi so when im trying to run ./run.bat it tries to connect to mongodb for a while but it doesnt work, how do i fix that?

Connecting to MongoDB...
server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: dial tcp [::1]:27017: connectex: No connection could be made because the target machine actively refused it. }, ] }
goroutine 1 [running, locked to thread]:
tf2-rcon/utils.PrintStackTrace({0xf44660?, 0xc0001cad70?})
        C:/Users/Dave/dave/stuff/TF2-RCON-MISC/utils/tf2.go:61 +0x85
tf2-rcon/utils.ErrorHandler({0xf44660?, 0xc0001cad70?}, 0xd0?)
        C:/Users/Dave/dave/stuff/TF2-RCON-MISC/utils/tf2.go:46 +0x6f
tf2-rcon/db.connect()
        C:/Users/Dave/dave/stuff/TF2-RCON-MISC/db/db.go:51 +0x1ef
tf2-rcon/db.init()
        C:/Users/Dave/dave/stuff/TF2-RCON-MISC/db/db.go:16 +0x19

**Comment by algo7** [comment]
For that, you will have to install https://www.mongodb.com/try/download/community

We will make it optional in the future so one can also use it without MongoDB.

**Comment by DavidDubinin** [comment]
alright, thank you! a friend of mine saw this in a game and i thought it was super cool so i wanted to try it out myself. i recommend you make it clear in the readme that mongodb and go are required, because my monkey brain managed to figure out i had to install go but not mongodb.
